services:
  scheduler:
    volumes:
      - .:/usr/local/airflow
    user: "astro:astro"
  webserver:
    volumes:
      - .:/usr/local/airflow
    user: "astro:astro"
  triggerer:
    volumes:
      - .:/usr/local/airflow
    user: "astro:astro"