services:
  scheduler:
    volumes:
      - ./data:/usr/local/airflow/data
    user: "astro:astro"
  webserver:
    volumes:
      - ./data:/usr/local/airflow/data
    user: "astro:astro"
  triggerer:
    volumes:
      - ./data:/usr/local/airflow/data
    user: "astro:astro"